import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import localFont from 'next/font/local';
import "./globals.css";

const firaCode = localFont({
    src: [
        {
            path: './../public/fonts/FiraCode-Regular.ttf',
            weight: '400',
            style: 'normal',
        },
        {
            path: './../public/fonts/FiraCode-Retina.ttf',
            weight: '450',
            style: 'normal',
        },
        {
            path: './../public/fonts/FiraCode-Medium.ttf',
            weight: '500',
            style: 'normal',
        },
    ], 
})

export const metadata: Metadata = {
    title: "Sagdiev Ruslan | Frontend Developer Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body className={`${firaCode.className} font-retina text-gray text-body p-[30px] bg-background h-screen`}>
                <div className="flex flex-col justify-between bg-black-light border rounded-lg h-full">
                    <Header />
                    {children}
                    <Footer />
                </div>
            </body>
        </html>
    );
}
